name: Tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:

  just-pass:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Just pass"

  pest-tests:
    if: false
    uses: ./.github/workflows/run-pest-tests.yml

  e2e-tests:
    if: false
    uses: ./.github/workflows/run-e2e-tests.yml
